/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "LibrarieX_1.h"
#include <cassert>

int main() {
    LibrarieX_1::Variants Variant ;
    assert(Variants.Variant().compare("Ceci est une LibrarieX_1") == 0);
    return 0;
}
