/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "LibrarieX_1.h"

std::string LibrarieX_1::Variants::Variant() {
    return std::string("Ceci est une LibrarieX_1");
}
