/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LIBRARIEX_1_H
#define LIBRARIEX_1_H

#ifdef _WIN32
#define LIBRARIEX_1_EXPORT_FUNC __declspec(dllexport)
#else
#define LIBRARIEX_1_EXPORT_FUNC
#endif

#include <string>

namespace LibrarieX_1 {
    class Variants {
        public:
        std::string LIBRARIEX_1_EXPORT_FUNC Variant();
    };
}

#endif
